@startuml

title 1부터 100 사이의 홀수 출력(1번)


start

:i = 1;
note right: 반복수 선언

while (\n  i <= 100?\n)  is (true)
  if (i가 홀수?) then (true) 
    :i 출력;
  else (false)
  endif
  :i++;
  note right: 반복수 증가
endwhile (false)

stop

@enduml