@startuml

title 카운트 구하기


start

#application:카운트 = 0;
note left: 카운트 변수 선언

:i = 1;
note right: 반복수 선언

while (\n  i <= 100?\n)  is (true)
  if (i가 짝수?) then (true)
    #application:카운트 1 증가;
  else (false)
    :카운트 변화 없음;
  endif
  :i++;
  note right: 반복수 증가
endwhile (false)

#application:카운트 출력;

stop

@enduml
